### PR TITLE
Update .depend

### LINKED ISSUE #1078: pixmaps.ml: Error: Unbound module Bytearray
Sorry for not noticing the build failures with b24b600 earlier:

````
....
[   31s] + /usr/bin/make -O -j4 PREFIX=/usr
....
[   31s] make[1]: Entering directory '/home/abuild/rpmbuild/BUILD/unison-20241102T085235.b24b600/src'
[   31s] ocamlopt: pixmaps.ml ---> pixmaps.cmx
[   31s] ocamlopt -g -I lwt -I ubase -I system -I +unix -I +str -I system/generic -I lwt/generic -I +lablgtk3 -I +cairo2 -c /home/abuild/
rpmbuild/BUILD/unison-20241102T085235.b24b600/src/pixmaps.ml
[   31s] File "/home/abuild/rpmbuild/BUILD/unison-20241102T085235.b24b600/src/pixmaps.ml", line 260, characters 12-28:
[   31s] 260 |   let buf = Bytearray.create sz in
[   31s]                   ^^^^^^^^^^^^^^^^
[   31s] Error: Unbound module Bytearray
[   31s] Hint: Did you mean Bigarray?
[   31s] make[1]: *** [Makefile.OCaml:426: pixmaps.cmx] Error 2
[   31s] make[1]: Leaving directory '/home/abuild/rpmbuild/BUILD/unison-20241102T085235.b24b600/src'
````

### PR DESCRIPTION
**Pull request by tleedjarv**
Add missing dependencies that broke parallel builds. Non-parallel builds are not impacted.

Fixes #1078

### CODE REVIEW

**Comment by gdt** [comment]
I'm not averse to this, but I'm having trouble following and I'd like to get unconfused.  I do understand the point of having a dependency expressed.    I ran "gmake -j50" without issues -- but I don't have the GUI prereqs.  However, my build output doesn't look parallel.   Are you simply doing "${GMAKE} -j16" at top level?

**Comment by gdt** [comment]
I meant that without the GUI prereqs installed, the build system doesn't build unison-gui and hence doesn't get into pixmap in the first place.

Indeed the diff is different.  It's just that I am used to BSD make which makes parallel operation much more apparent.
