### ISSUE TITLE
build fails with ocaml 4.12

### ISSUE THREAD

**Issue by fjaell** [bcpierce00/unison#487]
building unison 2.51.4_rc1 works with ocaml 4.11.1 but fails with ocaml 4.12:

/usr/bin/ld: update.o: in function `camlUpdate__checkArchive_385':
/tmp/unison/src/unison-2.51.4_rc1/src/uutil.ml:39: undefined reference to `caml_hash_univ_param'
/usr/bin/ld: /tmp/unison/src/unison-2.51.4_rc1/src/uutil.ml:39: undefined reference to `caml_hash_univ_param'
/usr/bin/ld: props.o: in function `camlProps__hash_548':
/tmp/unison/src/unison-2.51.4_rc1/src/uutil.ml:39: undefined reference to `caml_hash_univ_param'
/usr/bin/ld: props.o: in function `camlProps__hash_1237':
/tmp/unison/src/unison-2.51.4_rc1/src/uutil.ml:39: undefined reference to `caml_hash_univ_param'
/usr/bin/ld: case.o: in function `camlCase__fun_543':
/tmp/unison/src/unison-2.51.4_rc1/src/uutil.ml:39: undefined reference to `caml_hash_univ_param'
/usr/bin/ld: case.o:/tmp/unison/src/unison-2.51.4_rc1/src/uutil.ml:39: more undefined references to `caml_hash_univ_param' follow
collect2: error: ld returned 1 exit status
File "caml_startup", line 1:
Error: Error during linking (exit code 1)

**Comment by gdt** [comment]
See #480, #481.   Test reports and code reviews welcome.

**Comment by dhull** [comment]
I want to report success. Compiling unison-2.51.3 with ocaml 4.12.0 failed with the "undefined reference to 'caml_hash_univ_param'" error but unison-2.51.4_rc2 compiled successfully with the same ocaml version.

**Comment by gdt** [comment]
Just noticed the success report.  Fixed in rc counts as fixed!

**Comment by AbhisekGIT** [comment]
@dhull Thanks a ton...
